spring:
  mail:
  host: smtp.gmail.com
  port: 587
    username: 본인의 구글 계정 @gmail.com
  password: 본인의 구글 계정 비밀번호
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace